export const AUTH_LOGIN_REQUEST: string  = 'AUTH/LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS: string  = 'AUTH/LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE: string  = 'AUTH/LOGIN_FAILURE';

export const AUTH_LOGOUT_ACTION: string  = 'AUTH/LOGOUT_ACTION';

export const AUTH_VALIDATE_REQUEST: string  = 'AUTH/VALIDATE_REQUEST';
export const AUTH_VALIDATE_SUCCESS: string  = 'AUTH/VALIDATE_SUCCESS';
export const AUTH_VALIDATE_FAILURE: string  = 'AUTH/VALIDATE_FAILURE';

export const AUTH_TOKENS_REQUEST: string  = 'AUTH/SET_TOKENS_REQUEST';
export const AUTH_TOKENS_SUCCESS: string  = 'AUTH/SET_TOKENS_SUCCESS';
export const AUTH_TOKENS_FAILURE: string  = 'AUTH/SET_TOKENS_FAILURE';
